apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml

namespace: pyapp

images:
- name: pyapp
  newName: pavankumarag/python-flask-docker
  newTag: b5bf1164652ae2909c02d11bf763ebcca72fc3e7
