apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml

namespace: pyapp

images:
- name: pyapp
  newName: pavankumarag/python-flask-docker
  newTag: d3c59bae2d12a36266107a87848dc8cfb50af759
